language: c
os: linux

compiler: gcc


addons:
    apt:
        update: true
        packages:
            - autoconf
            - ocaml-nox
            - camlidl
            - coccinelle
            - libocamlnet-ocaml-dev
            - libocamlnet-ssl-ocaml
            - libocamlnet-ssl-ocaml-dev
            - libocamlnet-ocaml-bin
            - libconfig-file-ocaml-dev
            - camlp4
            - libssl-dev

script:
    - ./autogen.sh
    - ./configure --with-idlgen --with-rpcgen --with-libnames=foo --with-ssl --with-ssl-clientfiles='env'
    - make

jobs:
    include:
        - os: linux
          dist: trusty
        - os: linux
          dist: xenial
        - os: linux
          dist: bionic
