language: c
os: linux

compiler: gcc

before_install:
    - sudo apt-get update
    - sudo apt-get -y install sudo apt-get install autoconf make gcc ocaml-nox camlidl coccinelle libocamlnet-ocaml-dev libocamlnet-ocaml-bin libconfig-file-ocaml-dev camlp4


script:
    - ./autogen.sh && ./configure --with-idlgen --with-rpcgen --with-libnames=foo && make
