language: c

compiler: gcc
services: docker

dist: bionic

jobs:
    include:
      - stage: Debian builds
        name: Stretch
        script: docker build -t caml-crush-stretch --build-arg flavor=stretch -f Dockerfile.debian .
      -  
        name: Jessie
        script: docker build -t caml-crush-jessie --build-arg flavor=jessie -f Dockerfile.debian .
      -  
        name: Buster
        script: docker build -t caml-crush-buster --build-arg flavor=buster -f Dockerfile.debian .
      -  
        name: Sid
        script: docker build -t caml-crush-sid --build-arg flavor=sid -f Dockerfile.debian .
      - stage: Ubuntu builds
        name: Trusty
        script: docker build -t caml-crush-trusty -f Dockerfile.ubuntu-trusty .
      -  
        name: Jammy
        script: docker build -t caml-crush-jammy --build-arg dist=ubuntu --build-arg flavor=jammy -f Dockerfile.debian .
      -  
        name: Xenial
        script: docker build -t caml-crush-xenial --build-arg dist=ubuntu --build-arg flavor=xenial -f Dockerfile.debian .
      -  
        name: Bionic
        script: docker build -t caml-crush-bionic --build-arg dist=ubuntu --build-arg flavor=bionic -f Dockerfile.debian .
