language: c

compiler: gcc

addons:
    apt:
        update: true
        packages:
            - autoconf
            - ocaml-nox
            - camlidl
            - coccinelle
            - libocamlnet-ocaml-dev
            - libocamlnet-ssl-ocaml
            - libocamlnet-ssl-ocaml-dev
            - libocamlnet-ocaml-bin
            - libconfig-file-ocaml-dev
            - camlp4
            - libssl-dev
            - gnutls-dev

script:
    - ./autogen.sh
    - ./configure --with-idlgen --with-rpcgen --with-libnames=foo --with-ssl --with-ssl-clientfiles='env'
    - make

jobs:
    include:
        - os: linux
          dist: trusty
          addons:   
            apt:
              update: true
              packages:
                  - autoconf
                  - ocaml-nox
                  - camlidl
                  - coccinelle
                  - libocamlnet-ocaml-dev
                  - libocamlnet-ssl-ocaml
                  - libocamlnet-ssl-ocaml-dev
                  - libocamlnet-ocaml-bin
                  - libconfig-file-ocaml-dev
                  - camlp4
                  - libssl-dev
                  - libgnutls-dev
                  - ca-certificates
                  - pkg-config
                  - ocaml-findlib
          before_script:
                - wget http://download.camlcity.org/download/findlib-1.5.6.tar.gz -O /tmp/findlib-1.5.6.tar.gz
                - cd /tmp && tar xzf findlib-1.5.6.tar.gz && cd findlib-1.5.6 && ./configure && make all && sudo make install
                - wget https://github.com/savonet/ocaml-ssl/releases/download/0.5.5/ocaml-ssl-0.5.5.tar.gz -O /tmp/ocaml-ssl-0.5.5.tar.gz
                - cd /tmp && tar xzf /tmp/ocaml-ssl-0.5.5.tar.gz && cd ocaml-ssl-0.5.5 && ./configure && make && sudo make install
                - cd && cd calderonth/caml-crush
        - os: linux
          dist: xenial
        - os: linux
          dist: bionic
