#!/usr/bin/dh-exec
build-UNIX_CLIENT/usr/lib/${DEB_HOST_MULTIARCH}/caml-crush/libp11client.so => /usr/lib/${DEB_HOST_MULTIARCH}/caml-crush/libp11clientunix.so
build-TCP_CLIENT/usr/lib/${DEB_HOST_MULTIARCH}/caml-crush/libp11client.so => /usr/lib/${DEB_HOST_MULTIARCH}/caml-crush/libp11clienttcp.so
build-SERVER/usr/lib/${DEB_HOST_MULTIARCH}/caml-crush/libp11client.so => /usr/lib/${DEB_HOST_MULTIARCH}/caml-crush/libp11clienttcpssl.so
